CREATE SEQUENCE IF NOT EXISTS order_sequence_number_seq AS BIGINT START WITH 1;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS trader_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS users_trader_id_uidx ON users (trader_id);

ALTER TABLE instruments
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS matching_group SMALLINT NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX IF NOT EXISTS instruments_numeric_id_uidx ON instruments (id);
ALTER TABLE instruments DROP CONSTRAINT IF EXISTS instruments_matching_group_check;
ALTER TABLE instruments
    ADD CONSTRAINT instruments_matching_group_check CHECK (matching_group IN (1, 2));

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS trader_id BIGINT,
    ADD COLUMN IF NOT EXISTS limit_price_ticks BIGINT,
    ADD COLUMN IF NOT EXISTS stop_price_ticks BIGINT,
    ADD COLUMN IF NOT EXISTS sequence_number BIGINT DEFAULT nextval('order_sequence_number_seq');

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_order_type_check;

UPDATE orders o
SET trader_id = u.trader_id,
    limit_price_ticks = CASE WHEN o.limit_price IS NULL THEN NULL ELSE round(o.limit_price / i.tick_size)::BIGINT END,
    stop_price_ticks = CASE WHEN o.stop_price IS NULL THEN NULL ELSE round(o.stop_price / i.tick_size)::BIGINT END,
    sequence_number = COALESCE(o.sequence_number, nextval('order_sequence_number_seq'))
FROM users u, instruments i
WHERE o.user_id = u.user_id
  AND o.instrument_id = i.instrument_id
  AND (o.trader_id IS NULL OR o.sequence_number IS NULL OR
       (o.limit_price IS NOT NULL AND o.limit_price_ticks IS NULL) OR
       (o.stop_price IS NOT NULL AND o.stop_price_ticks IS NULL));

UPDATE orders SET status = 'PENDING' WHERE status = 'NEW';
UPDATE orders SET status = 'OPEN' WHERE status = 'ACCEPTED';

ALTER TABLE orders
    ALTER COLUMN trader_id SET NOT NULL,
    ALTER COLUMN sequence_number SET NOT NULL,
    ALTER COLUMN version SET DEFAULT 1;
UPDATE orders SET version = 1 WHERE version = 0;

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_remaining_quantity_check;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_check;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_check1;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_check2;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_trader_fk;
ALTER TABLE orders
    ADD CONSTRAINT orders_status_check CHECK (status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED')),
    ADD CONSTRAINT orders_order_type_check CHECK (order_type IN ('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT')),
    ADD CONSTRAINT orders_quantity_integer_check CHECK (quantity = trunc(quantity)),
    ADD CONSTRAINT orders_remaining_quantity_check CHECK (remaining_quantity >= 0 AND remaining_quantity <= quantity AND remaining_quantity = trunc(remaining_quantity)),
    ADD CONSTRAINT orders_limit_ticks_check CHECK (limit_price_ticks IS NULL OR limit_price_ticks > 0),
    ADD CONSTRAINT orders_stop_ticks_check CHECK (stop_price_ticks IS NULL OR stop_price_ticks > 0),
    ADD CONSTRAINT orders_required_limit_ticks_check CHECK (order_type NOT IN ('LIMIT', 'STOP_LIMIT') OR limit_price_ticks IS NOT NULL),
    ADD CONSTRAINT orders_required_stop_ticks_check CHECK (order_type NOT IN ('STOP', 'STOP_LIMIT') OR stop_price_ticks IS NOT NULL),
    ADD CONSTRAINT orders_trader_fk FOREIGN KEY (trader_id) REFERENCES users(trader_id);

CREATE UNIQUE INDEX IF NOT EXISTS orders_numeric_id_uidx ON orders (id);
CREATE UNIQUE INDEX IF NOT EXISTS orders_client_order_id_uidx ON orders (client_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS orders_sequence_number_uidx ON orders (sequence_number);
CREATE INDEX IF NOT EXISTS orders_id_lookup_idx ON orders (id);
CREATE INDEX IF NOT EXISTS orders_trader_history_idx ON orders (trader_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS orders_active_instrument_idx ON orders (instrument_id, sequence_number)
    WHERE status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED');
CREATE INDEX IF NOT EXISTS orders_active_buy_limits_idx ON orders (instrument_id, limit_price_ticks DESC, sequence_number ASC)
    WHERE side = 'BUY' AND order_type IN ('LIMIT', 'STOP_LIMIT') AND status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED');
CREATE INDEX IF NOT EXISTS orders_active_sell_limits_idx ON orders (instrument_id, limit_price_ticks ASC, sequence_number ASC)
    WHERE side = 'SELL' AND order_type IN ('LIMIT', 'STOP_LIMIT') AND status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED');
CREATE INDEX IF NOT EXISTS orders_active_stops_idx ON orders (instrument_id, stop_price_ticks, sequence_number)
    WHERE order_type IN ('STOP', 'STOP_LIMIT') AND status IN ('PENDING', 'OPEN', 'PARTIALLY_FILLED');

CREATE TABLE IF NOT EXISTS executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id VARCHAR(128) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    trader_id BIGINT NOT NULL REFERENCES users(trader_id),
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    execution_price_ticks BIGINT NOT NULL CHECK (execution_price_ticks > 0),
    execution_quantity BIGINT NOT NULL CHECK (execution_quantity > 0),
    market_bid_ticks BIGINT CHECK (market_bid_ticks > 0),
    market_ask_ticks BIGINT CHECK (market_ask_ticks > 0),
    price_source VARCHAR(64) NOT NULL,
    market_timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS executions_order_idx ON executions (order_id, created_at, id);

CREATE TABLE IF NOT EXISTS order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    event_type VARCHAR(64) NOT NULL,
    event_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_events_order_idx ON order_events (order_id, created_at, id);

INSERT INTO instruments
    (symbol, name, asset_class, exchange, currency, tick_size, lot_size, contract_size,
     market_data_provider, provider_symbol, status, matching_group)
VALUES
    ('NVDA', 'NVIDIA Corporation', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'NVDA', 'ACTIVE', 1),
    ('AAPL', 'Apple Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'AAPL', 'ACTIVE', 1),
    ('MSFT', 'Microsoft Corporation', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'MSFT', 'ACTIVE', 1),
    ('TSLA', 'Tesla Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'TSLA', 'ACTIVE', 1),
    ('AMZN', 'Amazon.com Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'AMZN', 'ACTIVE', 1),
    ('GOOGL', 'Alphabet Inc. Class A', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'GOOGL', 'ACTIVE', 1),
    ('META', 'Meta Platforms Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'META', 'ACTIVE', 1),
    ('AVGO', 'Broadcom Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'AVGO', 'ACTIVE', 1),
    ('AMD', 'Advanced Micro Devices Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'AMD', 'ACTIVE', 1),
    ('MU', 'Micron Technology Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'MU', 'ACTIVE', 1),
    ('ORCL', 'Oracle Corporation', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'ORCL', 'ACTIVE', 1),
    ('PLTR', 'Palantir Technologies Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'PLTR', 'ACTIVE', 1),
    ('NFLX', 'Netflix Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'NFLX', 'ACTIVE', 1),
    ('WMT', 'Walmart Inc.', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'WMT', 'ACTIVE', 1),
    ('COST', 'Costco Wholesale Corporation', 'EQUITY', 'NASDAQ', 'USD', 0.01, 1, 1, 'ALPACA', 'COST', 'ACTIVE', 1),
    ('HD', 'Home Depot Inc.', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'HD', 'ACTIVE', 2),
    ('JPM', 'JPMorgan Chase & Co.', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'JPM', 'ACTIVE', 2),
    ('BAC', 'Bank of America Corporation', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'BAC', 'ACTIVE', 2),
    ('V', 'Visa Inc.', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'V', 'ACTIVE', 2),
    ('MA', 'Mastercard Incorporated', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'MA', 'ACTIVE', 2),
    ('LLY', 'Eli Lilly and Company', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'LLY', 'ACTIVE', 2),
    ('JNJ', 'Johnson & Johnson', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'JNJ', 'ACTIVE', 2),
    ('UNH', 'UnitedHealth Group Incorporated', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'UNH', 'ACTIVE', 2),
    ('ABBV', 'AbbVie Inc.', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'ABBV', 'ACTIVE', 2),
    ('XOM', 'Exxon Mobil Corporation', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'XOM', 'ACTIVE', 2),
    ('CVX', 'Chevron Corporation', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'CVX', 'ACTIVE', 2),
    ('GE', 'GE Aerospace', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'GE', 'ACTIVE', 2),
    ('CAT', 'Caterpillar Inc.', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'CAT', 'ACTIVE', 2),
    ('BA', 'Boeing Company', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'BA', 'ACTIVE', 2),
    ('PG', 'Procter & Gamble Company', 'EQUITY', 'NYSE', 'USD', 0.01, 1, 1, 'ALPACA', 'PG', 'ACTIVE', 2)
ON CONFLICT (market_data_provider, provider_symbol) DO UPDATE
SET name = EXCLUDED.name,
    tick_size = EXCLUDED.tick_size,
    status = EXCLUDED.status,
    matching_group = EXCLUDED.matching_group,
    updated_at = now();

ALTER TABLE instruments
    ADD COLUMN IF NOT EXISTS active BOOLEAN GENERATED ALWAYS AS (status = 'ACTIVE') STORED;
